version: '1'

services:
  fastapi-app:
    platform: linux/amd64
    command: bash -c "uvicorn api:app --host 0.0.0.0 --port 8001 --reload"
    build: .
    container_name: smektep-api
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 4g
   

